FUNCTION ZSUSR_TCODES_LIST_BOTH.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(SELTYPE)
*"     VALUE(NAME)
*"     VALUE(NAME2) OPTIONAL
*"     VALUE(COMPARE) LIKE  USSEL1-SELTYPE
*"  TABLES
*"      TCODES STRUCTURE  USSEL1
*"      E_TEMPTSTCT STRUCTURE  TSTCT
*"----------------------------------------------------------------------
  DATA SEL.
  DATA: TCODES_BEFORE LIKE TCODES OCCURS 100 WITH HEADER LINE.
  DATA: BEGIN OF IT_TSTC OCCURS 0,
             TCODE LIKE TSTCT-TCODE,
        END OF IT_TSTC.
  DATA: BEGIN OF IT_TSTCT OCCURS 0,
             TCODE LIKE TSTCT-TCODE,
             TTEXT LIKE TSTCT-TTEXT,
        END OF IT_TSTCT.
  DATA: WA_TSTCT LIKE LINE OF IT_TSTCT.

  SORT TCODES BY LOW.
  DELETE ADJACENT DUPLICATES FROM TCODES.   " note 0156657
  REFRESH: TEMPTSTCT1.
* Doppelte Eintrage einmal mit 'S' (S_TCODE), einmal mit 'T'
* werden durch einen einzelnen mit 'B' ersetzt
  LOOP AT TCODES.
    IF TCODES_BEFORE-LOW EQ TCODES-LOW
      AND TCODES_BEFORE-SELTYPE NE TCODES-SELTYPE .
      TCODES_BEFORE-SELTYPE = 'B'.
    ELSE.
      APPEND TCODES_BEFORE.
      MOVE-CORRESPONDING TCODES TO TCODES_BEFORE.
    ENDIF.
  ENDLOOP.
  APPEND TCODES_BEFORE.

  IF COMPARE EQ 'B'.
    loop at TCODES_BEFORE WHERE SELTYPE EQ 'B'.
      IT_TSTC-tcode = TCODES_BEFORE-low.
      append IT_TSTC.
    endloop.
  ELSEIF COMPARE EQ 'C'.
    loop at TCODES_BEFORE.
      IT_TSTC-tcode = TCODES_BEFORE-low.
      append IT_TSTC.
    endloop.
  ENDIF.
  SELECT TCODE TTEXT FROM TSTCT INTO TABLE IT_TSTCT
    for all entries in IT_TSTC
    WHERE SPRSL EQ SY-LANGU
      and tcode = IT_TSTC-tcode.
  sort IT_TSTCT by TCODE.

  IF COMPARE EQ 'C'.
    LOOP AT TCODES_BEFORE.
      clear WA_TSTCT.
      READ TABLE IT_TSTCT WITH KEY TCODE = TCODES_BEFORE-LOW
        INTO WA_TSTCT
        BINARY SEARCH.
      TEMPTSTCT1-TCODE   = TCODES_BEFORE-LOW.
      TEMPTSTCT1-TTEXT   = WA_TSTCT-TTEXT.
      TEMPTSTCT1-SELTYPE = TCODES_BEFORE-SELTYPE.
      APPEND TEMPTSTCT1.
    ENDLOOP.
  ELSEIF COMPARE EQ 'B'.
    LOOP AT TCODES_BEFORE WHERE SELTYPE EQ 'B'.
      clear WA_TSTCT.
      READ TABLE IT_TSTCT WITH KEY TCODE = TCODES_BEFORE-LOW
        INTO WA_TSTCT
        BINARY SEARCH.
      TEMPTSTCT-TCODE    = TCODES_BEFORE-LOW.
      TEMPTSTCT-TTEXT    = WA_TSTCT-TTEXT.
      APPEND TEMPTSTCT.
    ENDLOOP.
  ENDIF.
  SELTYP = SELTYPE.
  TITLE1 = NAME.
  TITLE2 = NAME2.
  CLEAR FERTIG.
  IF COMPARE = 'C'.
    SORT: TEMPTSTCT1 BY TCODE.
*    CALL SCREEN 255.
  ELSEIF COMPARE = 'B'.
    SORT: TEMPTSTCT BY TCODE.
*    CALL SCREEN 254.
  ENDIF.
  E_TEMPTSTCT[] = TEMPTSTCT[].
ENDFUNCTION.
